language: python
python:
  - "3.7"
install:
  - pip install .
  - pip install keyrings.alt
  - pip install coverage
  - pip install coveralls
  - pip install flake8
script:
  - flake8 --ignore E501,E722
  - coverage run --source=aws_google_auth/ --omit=aws_google_auth/tests/* setup.py test
after_script:
  - coverage report
after_success:
  - coveralls

jobs:
  include:
  - stage: Docker Build Test
    script: docker build -f Dockerfile .
  - stage: deploy
    install: skip
    script: skip
    deploy:
      provider: releases
      api_key:
        secure: YOUR_API_KEY_ENCRYPTED
      file_glob: true
      file: dist/*
      skip_cleanup: true
      on:
        tags: true
